language: r
# dist: bionic # Uncomment until fix of https://travis-ci.community/t/r-install-broken-travis-ci-rstudio-org-returns-403/9640
cache: packages

matrix:
  include:
  - r: release
    os: linux
    env: INSTALL_PURESEQTM=true
  - r: devel
    os: linux
    env: INSTALL_PURESEQTM=false
  # Mac is not supported by PureseqTM
  #- r: release
  #  os: osx

r_github_packages:
  - r-lib/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice

before_install:
  # libgit2-dev
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install libgit2-dev; fi

before_script:
  - if [[ "$INSTALL_PURESEQTM" == true ]]; then ./scripts/install_pureseqtm.sh; fi

after_success:
  - if [[ "$INSTALL_PURESEQTM" == false ]]; then Rscript -e 'lintr::lint_package()'; fi
  - if [[ "$INSTALL_PURESEQTM" == true ]]; then Rscript -e 'covr::codecov()'; fi
  - if [[ "$INSTALL_PURESEQTM" == true ]]; then Rscript -e 'goodpractice::gp()'; fi
  - # No local files created
  - if [[ $(egrep -R "\"~" --include={*.R,*.Rmd}) ]]; then echo "Local file created"; exit 1; fi;
  - # Report
  - Rscript -e 'pureseqtmr::pureseqtmr_report()'
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

after_failure:
  - Rscript -e 'pureseqtmr::pureseqtmr_report()'
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf


