test_that("use", {
  expect_silent(check_pureseqtm_mode("proteome"))
  expect_silent(check_pureseqtm_mode("protein"))
  expect_error(check_pureseqtm_mode("nonsense"))
  expect_error(check_pureseqtm_mode(""))
  expect_error(check_pureseqtm_mode(NA))
  expect_error(check_pureseqtm_mode(NULL))
  expect_error(check_pureseqtm_mode(Inf))
  expect_error(check_pureseqtm_mode(3.14))
  expect_error(check_pureseqtm_mode(c("proteome", "proteome")))
})
