// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// load_fasta_file_as_tibble_cpp_raw
Rcpp::List load_fasta_file_as_tibble_cpp_raw(const Rcpp::String& fasta_filename);
RcppExport SEXP _pureseqtmr_load_fasta_file_as_tibble_cpp_raw(SEXP fasta_filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::String& >::type fasta_filename(fasta_filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(load_fasta_file_as_tibble_cpp_raw(fasta_filename));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pureseqtmr_load_fasta_file_as_tibble_cpp_raw", (DL_FUNC) &_pureseqtmr_load_fasta_file_as_tibble_cpp_raw, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_pureseqtmr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
