# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Use Rcpp to load a FASTA file
#' @param fasta_filename FASTA filename
#' @return a list with two character vectors,
#'   named 'name' and 'sequence'
load_fasta_file_as_tibble_cpp_raw <- function(fasta_filename) {
    .Call('_pureseqtmr_load_fasta_file_as_tibble_cpp_raw', PACKAGE = 'pureseqtmr', fasta_filename)
}

