# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Use Rcpp to calculate the distance to a TMH center
#' @param topology_str a topology as a string
#' @return a vector with distances
calc_distance_to_tmh_center_from_topology_str_cpp_stl <- function(topology_str) {
    .Call('_pureseqtmr_calc_distance_to_tmh_center_from_topology_str_cpp_stl', PACKAGE = 'pureseqtmr', topology_str)
}

#' Use Rcpp to load a FASTA file
#' @param fasta_filename FASTA filename
#' @return a list with two character vectors,
#'   named 'name' and 'sequence'
load_fasta_file_as_tibble_cpp_raw <- function(fasta_filename) {
    .Call('_pureseqtmr_load_fasta_file_as_tibble_cpp_raw', PACKAGE = 'pureseqtmr', fasta_filename)
}

